apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pythonflaskapp
  template:
    metadata:
      labels:
        app: pythonflaskapp
    spec:
      containers:
        - name: pythonflaskapp
          image: notanima/csc_3104:latest
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              value: "postgresql://user:password@postgres-service:5432/mydatabase"
            - name: DOMAIN
              value: "dereknan.click"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: pythonflaskapp
  ports:
    - protocol: TCP
      port: 80  # The port on the service (external access)
      targetPort: 5000  # The port on the pods (containerPort)
  type: LoadBalancer  # Use 'LoadBalancer' type if you want to expose your service externally
