# Use an official Python runtime as a parent image
FROM arm64v8/python:3.10-slim-buster

# Set the working directory in the container
WORKDIR /app

# Copy the local directory contents into the container at /app
COPY . .

# Activate the virtual environment
RUN pip3 install -r requirements.txt

# Specify the command to run your Python script
CMD ["python","-u", "FD_server.py"]
