version: '3.8'
services:
  web:
    # image: dereknan/cloud-client:latest
    container_name: pythonFlaskApp
    build: 
      context: .
    ports:
      - "80:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    depends_on:
      - db
    networks:
      - cloudNet

  db:
    container_name: postgresdb
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cloudNet

networks:
  cloudNet: 

volumes:
  postgres_data: 

