# Use an official Python runtime as a parent image
FROM arm64v8/python:3.10-slim-buster

# Set the working directory in the container
WORKDIR /app

COPY ./requirements.txt .

RUN pip3 install -r requirements.txt

# Copy the local directory contents into the container at /app
COPY . .

# Specify the command to run your Python script
CMD ["python", "-u","train.py"]
